import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="center">Terry Seiple</h1>
        <div>
          <div className="flex items-center">
            <h2 className="text-2xl">
              <a href="https://github.com/seiplet93/Dim-Souls">Dim Souls</a>
            </h2>
            <p>
              A top-down, 2-D take on the souls-like game genre. Dim Souls is an
              ode to the Dark Souls franchise created with HTML Canvas and
              JavaScript.
            </p>
          </div>
          <Image
            // '/' assumes you are in the public folder

            src="/dim-souls.jpg"
            alt="dim souls"
            // width and height are required
            width={500}
            height={500}
          />
        </div>

        <div>
          <div>
            <h2 className="text-2xl">
              <a href="https://github.com/seiplet93/Tune-Town">Tune Town</a>
            </h2>
            <p>
              A social platform aimed at catalogging music first, and
              socializing second. Using the Audio DB API, this Express/EJS app
              allows users to create accounts, search for music, curate lists,
              and interact around others' lists.
            </p>
          </div>
          <Image
            // '/' assumes you are in the public folder

            src="/tunetown.jpg"
            alt="tune town"
            // width and height are required
            width={500}
            height={300}
          />
        </div>

        <div>
          <div>
            <h2 className="text-2xl">
              <a href="https://github.com/seiplet93/InCRUDibles-client">
                Check Mate
              </a>
            </h2>
            <p>
              Not your average checklist, Check Mate is a shared to-do list
              tracker. Think Netflix, but for your household's tasks. Create an
              account for your group, make a profile as a user, start and
              complete tasks as a group.
            </p>
          </div>
          <Image
            // '/' assumes you are in the public folder

            src="/checkmate.jpg"
            alt="RIP King"
            // width and height are required
            width={500}
            height={300}
          />
        </div>
      </main>
    </div>
  );
}
